name = "CY5"
uuid = "9d716e1b-4291-4ffc-b550-8d2805581b65"
authors = ["dh604 <daniel.holmes@gmx.at> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
