name = "CY5"
uuid = "9d716e1b-4291-4ffc-b550-8d2805581b65"
authors = ["Daniel Holmes <daniel.holmes@ist.ac.at>"]
version = "1.0.0-DEV"

[deps]
GKMtools = "cb0ce832-b756-443a-91cf-e9266e6225ad"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
GKMtools = "0.15.1"
Oscar = "1.6.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
