load_attach_path('boxcounting')
load("boxcounting/partition_3d.sage")
load("boxcounting/bare_vertex.sage")
load("boxcounting/edge.sage")
from itertools import product

def setup_ring(gens):
    """
    Sets up the function field in generators `gens` for performing vertex
    computations.
    """
    global wR
    global qR
    wR = LaurentPolynomialRing(QQ, gens)
    qR = LaurentSeriesRing(wR.fraction_field(), "q")
    for name, value in zip(wR.variable_names(), wR.gens()):
        globals()[name] = value
    globals()['q'] = qR.gen()

setup_ring('x,y,z')

def qshift(sh):
    """
    This function takes an element `sh` in `qR` and returns a morphism `qR` -> `qR`
    which substitutes the generator `q` by `sh` * `q`^2.
    """
    return Hom(qR, qR)([sh * q^2])

def nnn(part):
    """
    Takes a partition `part` and returns n_`part` = sum_{(i,j) in `part`} i where
    the boxes of `part` are labelled starting with (0,0) for the top left box.
    """
    return sum(i * part[i] for i in range(part.length()))

def E_NO_factor(part, LBdegs, wts):
    """
    This function returns the monomial by which an edge weight is shifted due to
    a Nekrasov-Okounkov insertion. This function takes as arguments a partition
    `part` decorating an edge, a 4-tuple of degrees `LBdegs` of each of the factors
    of the normal bundle of the edge in the fivefold and the 5-tuple tangent weights
    `wts` at the first fixed point of the edge.
    """
    exponent0 = (LBdegs[3]-LBdegs[2]) * (
        part.size() * (1 + LBdegs[2] + LBdegs[3]) / 2
        - (LBdegs[0] * nnn(part) + LBdegs[1] * nnn(part.conjugate()))
    )
    exponent1 = (LBdegs[3] - LBdegs[2]) * nnn(part)
    exponent2 = (LBdegs[3] - LBdegs[2]) * nnn(part.conjugate())
    exponent3 = part.size() - LBdegs[0] * nnn(part) - LBdegs[1] * nnn(part.conjugate())

    return (
        wts[0]^exponent0
        * wts[1]^exponent1
        * wts[2]^exponent2
        * (wts[3] / wts[4])^exponent3
        * (wts[3]^LBdegs[2] / wts[4]^LBdegs[3])^(part.size())
    )

def V(parts, wts, qprec):
    """
    Computes the vertex weight with a Nekrasov-Okounkov insertion. As arguments
    the function takes a 3-tuple `parts` of partitions, a 3- or 5-tuple of tangent
    weights `wts` and an integer `qprec` indicating the order in `q` to which the
    vertex shall be computed.
    """
    res = BareVertexPT(parts[0], parts[1], parts[2], KTheory).series(qprec)
    codomain = (wts[0] * wts[1] * wts[2]).parent().fraction_field()
    res = Default._apply_to_weight_ring(lambda f: f(wts[0], wts[1], wts[2]), res, codomain)
    
    if len(wts) == 3:
        return qshift(qR.one())(res)
    else:
        return qshift(wts[3] / wts[4])(res)

def E(part, LBdegs, wts):
    """
    Computes the edge weight with a Nekrasov-Okounkov insertion. As arguments
    the function takes a partition `part`, a 4-tuple of degrees `LBdegs` of each of
    the factors of the normal bundle of the edge in the fivefold and a 5-tuple of
    tangent weights `wts` at the first fixed point of the edge.
    """
    mu = Partition(part)
    edge_term = Edge(LBdegs[0], LBdegs[1], KTheory).term_q(mu, q=Default.q^2)
    codomain = (wts[0] * wts[1] * wts[2]).parent().fraction_field()
    edge_term = Default._apply_to_weight_ring(lambda f: f(wts[0], wts[1], wts[2]), edge_term, codomain)
    
    if len(wts) == 3:
        return edge_term
    else:
        return (
            (-1)^(LBdegs[3] * mu.size())
            * q^((LBdegs[2] + LBdegs[3]) * mu.size())
            * E_NO_factor(mu.conjugate(), LBdegs, wts)
            * edge_term
        )

def partition_list(d, n):
    """
    This function returns a list of `n` integer partitions [mu1, mu2, ...] such
    that d = sum_i sum_j mu_i[j].
    """
    dList = flatten([Permutations(dd + [0] * (n - len(dd))).list() for dd in Partitions(d, max_length=n).list()], max_level=1)
    return [list(muList) for dd in dList for muList in product(*[Partitions(di) for di in dd])]

def adams(k, QRR):
    """
    This function returns the `k`-th Adams operation in a power series ring `QRR`
    defined over some base ring which is generated by some variables (over again
    some other ring).
    """
    wKK = QRR.base_ring()
    adams_wKK = Hom(wKK, wKK)([qqi^k for qqi in wKK.gens()])
    adams_QRR = Hom(QRR, QRR)([Qi^k for Qi in QRR.gens()])
    return adams_QRR * Hom(QRR,QRR)(adams_wKK)

def Exp(f, dmax):
    """
    Computes the plethystic exponential of some (multivariable) formal Laurent
    series `f` up to some order `dmax`.
    """
    QRR = f.parent()
    if len(QRR.gens())==1:
        bigO = O(QRR.gen()^(dmax+1))
    else:
        bigO = QRR.O(dmax+1)
    g = sum(adams(k, QRR)(f)/k for k in range(1, dmax + 1)) + bigO
    return QRR.one() + sum(g^k / factorial(k) for k in range(1, dmax + 1))